import { useEffect, useRef } from 'react';
import type { GuardianConfig } from '../config/GuardianConfig.js';
import type { ThreatEvent } from '../events/ThreatEvent.js';
import type { EngineContext, Engine, EngineHealthTick } from '../engine/Engine.js';
import { PolicyEngine } from '../core/policy.js';
import { computeHmac } from '../core/HmacEnvelope.js';

// ─────────────────────────────────────────────────────────────────────────────
// useGuardian — primary SDK entry point
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Primary React hook. Mounts the guardian-rn SDK in a React component tree.
 *
 * ── What happens on mount ─────────────────────────────────────────────────
 *
 *   1. A new session UUID and a 32-byte cryptographic session key are generated.
 *
 *   2. A `signPayload` closure is created over the session key. This closure
 *      is the only way the key leaves this function — it is passed to
 *      PolicyEngine (which passes it to TelemetryAdapter.recordThreat) so
 *      adapters can sign outbound payloads without ever holding the raw bytes.
 *
 *   3. A PolicyEngine is instantiated with the current config and signPayload.
 *
 *   4. If sessionMaxAgeMs is configured, a timer is set to emit a
 *      `sessionExpiry` threat event at the configured age.
 *
 *   5. Each engine in config.engines is started sequentially (await engine.start()).
 *      Sequential start preserves ordering — if Engine B depends on Engine A
 *      being started first, list A before B in config.engines.
 *
 *   6. The PolicyEngine is subscribed to every engine's onThreat stream.
 *      Health ticks are forwarded to config.telemetry?.recordHealthTick().
 *
 *   7. An AppState listener is registered to call engine.throttle() when the
 *      app transitions between foreground and background.
 *
 * ── What happens on unmount ───────────────────────────────────────────────
 *
 *   1. The session expiry timer is cleared.
 *   2. All pending kill timers in PolicyEngine are cancelled.
 *   3. All engine onThreat and onHealthTick subscriptions are unsubscribed.
 *   4. All engines are stopped concurrently (fire-and-forget).
 *
 * ── configRef pattern ─────────────────────────────────────────────────────
 *
 * The hook captures config in a ref rather than using it directly in the
 * effect body. This avoids a known issue in freerasp-rn v4.x and similar
 * SDKs: if config is a new object reference on every render (because it is
 * constructed inline), the effect re-runs on every render if config is in
 * the dependency array — or uses a stale config if it is omitted.
 *
 * The ref approach: the effect runs once (empty dep array), but every call
 * to configRef.current reads the *latest* config at the moment of the call.
 * This correctly handles config updates without re-mounting the SDK.
 */
export function useGuardian(config: GuardianConfig): void {
  const configRef = useRef(config);
  // Always keep the ref current so that action callbacks, policies, and
  // telemetry adapters are always the latest ones — not the mount-time snapshot.
  configRef.current = config;

  useEffect(() => {
    // ── Session identity ──────────────────────────────────────────────────
    const sessionId  = generateSessionId();

    // 32-byte cryptographic key unique to this session. Generated by the
    // native GuardianKeyProvider TurboModule on real devices (Android Keystore
    // / iOS Secure Enclave). Falls back to Math.random() in test environments
    // where the native module is not available.
    const sessionKey = generateSessionKey();

    const subscriptions: Array<{ unsubscribe(): void }> = [];
    let policyEngine: PolicyEngine | null = null;
    let sessionExpiryTimer: ReturnType<typeof setTimeout> | null = null;

    // ── signPayload closure ───────────────────────────────────────────────
    // This closure captures sessionKey but does not expose the raw bytes.
    // Passing the closure to TelemetryAdapter means adapters get signing
    // capability without key material — following the principle of least
    // privilege. Per ADR-0014.
    const signPayload = (data: string): string =>
      computeHmac(data, sessionKey);

    // ── Engine context ────────────────────────────────────────────────────
    // Constructed once per mount. All engines in this session share the same
    // context object — they share the sessionId but have independent lifecycles.
    const ctx: EngineContext = {
      config: configRef.current,
      sessionId,
      platform: getPlatform(),
      managedProfile: false, // populated by ManagedProfileDetector at scan time
      onFault(error: Error) {
        // Faults are logged to the console in development. Production apps
        // should wire this to their crash reporter via config.telemetry.
        console.error('[guardian] engine fault:', error);
      },
    };

    const startAll = async (): Promise<void> => {
      policyEngine = new PolicyEngine(configRef.current, signPayload);

      // ── Session expiry timer ────────────────────────────────────────────
      // When sessionMaxAgeMs is set, synthesise a sessionExpiry ThreatEvent
      // after the configured duration. This models time-limited access tokens:
      // even if the underlying auth token is still valid, the SDK can force
      // a session reset at a configurable age.
      const maxAge = configRef.current.sessionMaxAgeMs;
      if (maxAge != null && maxAge > 0) {
        sessionExpiryTimer = setTimeout(() => {
          const expiryEvent: ThreatEvent = {
            threatId:  'sessionExpiry',
            severity:  'high',
            confidence: 1.0,  // expiry is deterministic — confidence is always 1.0
            evidence: {
              sessionId,
              maxAgeMs: String(maxAge),
            },
            ts:       Date.now(),
            engineId: 'guardian-rn/session',
          };
          policyEngine?.apply(expiryEvent);
        }, maxAge);
      }

      // ── Engine startup loop ─────────────────────────────────────────────
      // Engines start sequentially so that an engine that depends on
      // earlier engine state (e.g. BehavioralBaselineEngine observing
      // CommunityEngine) is correctly ordered.
      for (const engine of configRef.current.engines) {
        try {
          // start() must resolve before any threat event can be emitted —
          // this is the Engine interface invariant (ADR-0004 §1).
          await engine.start(ctx);

          // Subscribe to threats AFTER start() resolves. Using configRef
          // inside the callback rather than `config` avoids stale closures
          // when the parent component re-renders with updated callbacks.
          const threatSub = engine.onThreat.subscribe({
            next: (event: ThreatEvent) => policyEngine!.apply(event),
          });
          subscriptions.push(threatSub);

          const healthSub = engine.onHealthTick.subscribe({
            next: (tick: EngineHealthTick) =>
              configRef.current.telemetry?.recordHealthTick(tick),
          });
          subscriptions.push(healthSub);
        } catch (err) {
          // Engine failed to start — report as a fault but keep going.
          // A startup failure in one engine should not prevent others from
          // providing protection.
          ctx.onFault(err instanceof Error ? err : new Error(String(err)));
        }
      }

      // ── AppState throttle wiring ──────────────────────────────────────
      // Notify engines of foreground/background transitions so they can
      // reduce scan frequency when the app is not visible. This is the
      // battery-aware scan throttle (item 3 / ADR-0013).
      // The return value is an unsubscribe function — unused here because
      // we rely on React's cleanup to unmount the effect cleanly; the
      // AppState listener is implicitly removed when the component unmounts.
      wireAppStateThrottle(configRef.current.engines);
    };

    // Fire and forget: React's useEffect callback cannot be async directly.
    // The Promise is intentionally not awaited — mount errors are surfaced
    // via ctx.onFault, not by crashing the component.
    void startAll();

    // ── Cleanup ──────────────────────────────────────────────────────────
    return () => {
      if (sessionExpiryTimer !== null) clearTimeout(sessionExpiryTimer);
      policyEngine?.cancelPendingKills();
      for (const sub of subscriptions) sub.unsubscribe();
      // Stop all engines concurrently — order does not matter for shutdown.
      for (const engine of configRef.current.engines) void engine.stop();
    };

  // Empty dependency array: the SDK mounts once per component lifetime.
  // configRef.current is always fresh — no need to list `config` here.
  // eslint-disable-next-line -- engines array identity is intentionally stable
  }, []);
}

// ─────────────────────────────────────────────────────────────────────────────
// Internal helpers
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Subscribe to React Native's AppState 'change' event and forward transitions
 * to all engines that implement the optional throttle() method.
 *
 * The try/catch handles environments where react-native is not available
 * (Node test runner, Storybook). Engines that do not implement throttle()
 * are silently skipped via the optional-chaining call.
 */
function wireAppStateThrottle(engines: readonly Engine[]): (() => void) | undefined {
  try {
    const { AppState } = require('react-native') as {
      AppState: {
        addEventListener(
          event: string,
          cb: (state: string) => void,
        ): { remove(): void };
      };
    };
    const sub = AppState.addEventListener('change', (state: string) => {
      const mode = state === 'active' ? 'foreground' : 'background';
      for (const engine of engines) engine.throttle?.(mode);
    });
    return () => sub.remove();
  } catch {
    return undefined;
  }
}

/**
 * Generate a UUIDv4-compliant session identifier.
 *
 * Uses Math.random() as the entropy source — sufficient for session
 * correlation purposes, not for cryptographic key material. The session key
 * (generateSessionKey) uses a separate, stronger entropy source.
 */
function generateSessionId(): string {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}

/**
 * Generate a 32-byte cryptographic session key.
 *
 * On real devices, delegates to the GuardianKeyProvider TurboModule which
 * uses AndroidKeyStore (Android) or SecRandomCopyBytes (iOS) for CSPRNG-backed
 * generation. This ensures the key is generated in the platform's trusted
 * execution environment.
 *
 * Falls back to Math.random() in test and Storybook environments where the
 * native module is not linked. This fallback produces a key that is NOT
 * cryptographically secure — tests that rely on HMAC correctness must use
 * a fixed test key rather than this fallback.
 */
function generateSessionKey(): Uint8Array {
  try {
    const { NativeModules } = require('react-native') as {
      NativeModules: {
        GuardianKeyProvider?: { generateSessionKey(): number[] };
      };
    };
    const raw = NativeModules.GuardianKeyProvider?.generateSessionKey();
    if (raw && raw.length === 32) return new Uint8Array(raw);
  } catch { /* native module not available — fall through */ }

  // Test/CI fallback: Math.random is not a CSPRNG but is fine for unit tests.
  const key = new Uint8Array(32);
  for (let i = 0; i < 32; i++) key[i] = (Math.random() * 256) | 0;
  return key;
}

/**
 * Determine the current platform from React Native's Platform module.
 * Defaults to 'ios' in non-RN environments (e.g. test runner).
 */
function getPlatform(): 'android' | 'ios' {
  try {
    const { Platform } = require('react-native') as { Platform: { OS: string } };
    return Platform.OS === 'android' ? 'android' : 'ios';
  } catch {
    return 'ios';
  }
}
