#!/usr/bin/env tsx
/**
 * guardian-rn codegen
 * Reads packages/schema/threat-schema.json and writes:
 *   - packages/guardian-rn/src/generated/  (TypeScript)
 *   - packages/guardian-rn/android/src/main/kotlin/com/guardian/rn/generated/  (Kotlin)
 *   - packages/guardian-rn/ios/Generated/  (Swift)
 */
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';

const ROOT = resolve(__dirname, '../../..');
const SCHEMA_PATH = resolve(ROOT, 'packages/schema/threat-schema.json');

interface Schema {
  definitions: Record<string, SchemaDefinition>;
}

interface SchemaDefinition {
  type?: string;
  enum?: string[];
  description?: string;
  properties?: Record<string, unknown>;
  required?: string[];
  additionalProperties?: unknown;
}

function loadSchema(): Schema {
  return JSON.parse(readFileSync(SCHEMA_PATH, 'utf-8')) as Schema;
}

function ensureDir(path: string): void {
  mkdirSync(dirname(path), { recursive: true });
}

function write(path: string, content: string): void {
  ensureDir(path);
  writeFileSync(path, content, 'utf-8');
  console.log(`[codegen] ✓ ${path.replace(ROOT + '/', '')}`);
}

// ─── TypeScript ────────────────────────────────────────────────────────────

function generateTS(schema: Schema): void {
  const outDir = resolve(ROOT, 'packages/guardian-rn/src/generated');

  const defs = schema.definitions;

  // ThreatId
  const threatIds = (defs['ThreatId']?.enum ?? []).map((v) => `  | '${v}'`).join('\n');
  write(
    resolve(outDir, 'ThreatId.ts'),
    `// AUTO-GENERATED by packages/codegen — do not edit by hand\n` +
    `// Source: packages/schema/threat-schema.json\n\n` +
    `export type ThreatId =\n${threatIds};\n`,
  );

  // Severity
  const severities = (defs['Severity']?.enum ?? []).map((v) => `  | '${v}'`).join('\n');
  write(
    resolve(outDir, 'Severity.ts'),
    `// AUTO-GENERATED by packages/codegen — do not edit by hand\n\n` +
    `export type Severity =\n${severities};\n`,
  );

  // ResponsePolicy
  const policies = (defs['ResponsePolicy']?.enum ?? []).map((v) => `  | '${v}'`).join('\n');
  write(
    resolve(outDir, 'ResponsePolicy.ts'),
    `// AUTO-GENERATED by packages/codegen — do not edit by hand\n\n` +
    `export type ResponsePolicy =\n${policies};\n`,
  );

  // Barrel
  write(
    resolve(outDir, 'index.ts'),
    `// AUTO-GENERATED by packages/codegen — do not edit by hand\n\n` +
    `export type { ThreatId } from './ThreatId.js';\n` +
    `export type { Severity } from './Severity.js';\n` +
    `export type { ResponsePolicy } from './ResponsePolicy.js';\n`,
  );
}

// ─── Kotlin ────────────────────────────────────────────────────────────────

function generateKotlin(schema: Schema): void {
  const outDir = resolve(
    ROOT,
    'packages/guardian-rn/android/src/main/kotlin/com/guardian/rn/generated',
  );

  const threatIds = schema.definitions['ThreatId']?.enum ?? [];
  const objects = threatIds
    .map((id) => {
      const name = id.charAt(0).toUpperCase() + id.slice(1);
      return `    data object ${name} : ThreatId()`;
    })
    .join('\n');

  write(
    resolve(outDir, 'ThreatId.kt'),
    `// AUTO-GENERATED by packages/codegen — do not edit by hand\n` +
    `// Source: packages/schema/threat-schema.json\n\n` +
    `package com.guardian.rn.generated\n\n` +
    `sealed class ThreatId {\n${objects}\n}\n`,
  );

  const severities = schema.definitions['Severity']?.enum ?? [];
  const sevEntries = severities.map((s) => `    ${s.toUpperCase()}`).join(',\n');
  write(
    resolve(outDir, 'Severity.kt'),
    `// AUTO-GENERATED by packages/codegen — do not edit by hand\n\n` +
    `package com.guardian.rn.generated\n\n` +
    `enum class Severity {\n${sevEntries}\n}\n`,
  );

  const policies = schema.definitions['ResponsePolicy']?.enum ?? [];
  const polEntries = policies.map((p) => `    ${p.toUpperCase()}`).join(',\n');
  write(
    resolve(outDir, 'ResponsePolicy.kt'),
    `// AUTO-GENERATED by packages/codegen — do not edit by hand\n\n` +
    `package com.guardian.rn.generated\n\n` +
    `enum class ResponsePolicy {\n${polEntries}\n}\n`,
  );
}

// ─── Swift ────────────────────────────────────────────────────────────────

function generateSwift(schema: Schema): void {
  const outDir = resolve(ROOT, 'packages/guardian-rn/ios/Generated');

  const threatIds = schema.definitions['ThreatId']?.enum ?? [];
  const cases = threatIds.map((id) => `    case ${id}`).join('\n');
  write(
    resolve(outDir, 'ThreatId.swift'),
    `// AUTO-GENERATED by packages/codegen — do not edit by hand\n` +
    `// Source: packages/schema/threat-schema.json\n\n` +
    `public enum ThreatId: String, CaseIterable, Codable {\n${cases}\n}\n`,
  );

  const severities = schema.definitions['Severity']?.enum ?? [];
  const sevCases = severities.map((s) => `    case ${s}`).join('\n');
  write(
    resolve(outDir, 'Severity.swift'),
    `// AUTO-GENERATED by packages/codegen — do not edit by hand\n\n` +
    `public enum Severity: String, CaseIterable, Codable {\n${sevCases}\n}\n`,
  );

  const policies = schema.definitions['ResponsePolicy']?.enum ?? [];
  const polCases = policies.map((p) => `    case ${p}`).join('\n');
  write(
    resolve(outDir, 'ResponsePolicy.swift'),
    `// AUTO-GENERATED by packages/codegen — do not edit by hand\n\n` +
    `public enum ResponsePolicy: String, CaseIterable, Codable {\n${polCases}\n}\n`,
  );
}

// ─── Main ──────────────────────────────────────────────────────────────────

const schema = loadSchema();
generateTS(schema);
generateKotlin(schema);
generateSwift(schema);
console.log('[codegen] done');
